SELECT
	SUM(cc.TRANSACTION_VALUE), b.BRANCH_ZIP
FROM
	CDW_SAPP_HIVEDB.CREDITCARD cc JOIN CDW_SAPP_HIVEDB.BRANCH b
	ON (cc.BRANCH_CODE=b.BRANCH_CODE)
GROUP BY
	b.BRANCH_ZIP
ORDER BY
	SUM(cc.TRANSACTION_VALUE) DESC
limit 20;
