branch_details = LOAD '/Credit_Card_System/CDW_SAPP_BRANCH/part-r-00000' USING PigStorage(',') as (BRANCH_CODE:INT, BRANCH_NAME:CHARARRAY, BRANCH_STREET:CHARARRAY, BRANCH_CITY:CHARARRAY, BRANCH_STATE:CHARARRAY, BRANCH_ZIP:INT, BRANCH_PHONE:CHARARRAY, LAST_UPDATED:CHARARRAY);
NY_Branches = FILTER branch_details BY BRANCH_STATE == 'NY';
Dump NY_Branches;
